language: cpp
sudo: required
dist: bionic
env:
  matrix:
  - BUILD=windows
  - BUILD=native
os:
- linux
- osx
matrix:
  exclude:
  - os: osx
    env: BUILD=windows
install:
- "./build-scripts/travis-ci.sh setup_qt"
- "./build-scripts/travis-ci.sh get_quazip"
script:
- "./build-scripts/travis-ci.sh build"
before_deploy:
- "./build-scripts/travis-ci.sh package"
deploy:
- provider: s3
  access_key_id:
    secure: FLIdybRxjnMyhP7wfvWmQywYms61ZnX5yfABZs6cBE33MdDrJVnL9PqauBuyQ+1VZu81uz1VGvnVyQlnTYIncwlyxLGFPJ4Mi5yPsrVKh/OQ6kgiHHZHwLJB5S8RKF8Rtwp9p5DhxCBzuqCuuMKkaQmkefGGR0TRdEzcoxQx6uLhx+VCaCLoXEFJx7izV4lbDdBb8j3g1z+Se7kZSroMJRWB/ph//PpUQXiGHM3vsNDGXDtkn0s5gd40Ua89VL/kqfkQhNrmsmRlq3z5eUSzbRF5r1W1xBkaphVDTEmpFwv3HQZt1jbmPUckB1TSw1eG0kxqZ/zZPwgY3MwgXuS7dgxRN8sCfUmrWRyQjIv/pJ55clcKnt4Ql1kzKP2lkTWF2nInMl8DhHmFehgxLqLZg4+Ro6fHsrMZoM6nbGUfbR2eMDvbFVUz9yLaIp4mikcAYozdRQ1zlrD7226QzfjblLKuxfUlO8OF2OhF3jIPGAY4WjLq95jLX7MrWiOwXsv2fRNmAC4x40HT+Etufgz3f6BRZ4EUTqmfUTU3eNV7URiScBynqtVkRswy/FL1r1HnSatMDwF4Gfr79mMVHbVnPAApBrJPtlFsqNLqYit0kYqz2INLd54VmwELYVfGuR2woFMAgylyydRW99bDvr8USRVIHpfU3bV7QqRIJpqz08Q=
  secret_access_key:
    secure: WcQgb6f5iJWfoGKE9+URj62a7QvHekbE1RLIOaqXm0rQDnfkFcWc1I/oRLNmMel9yd+L4VwM+G4bTdwDYcdLU5KnEh808UK7Nq49K4zimHFeQdUyj0K1wSPMOP1jfImSCyTOU4e1x7JYNBlRrP0hGrVFDGqm3aoI7Qpcfj67jN5/psWoPZkOtQJ8Nse138v6x2OdlF7x+TmRKi7g7WD8eSIth+lJ5Tda7TMv7k42VgMr8z+RKUCfvOUEymSSYEODRPqUrulFYWugEM8pUlc+cyr2PgzBIYz4SYirbeRdIZLI3iRmGRqKq9Tz8szEsXnfJ/egvD3VmDHSal4EA6iFRp3/mDNJoupQP7dpKT71ti9ZhFm2Sfk6NE9wKYZG1NpAeobGCyysxhFVMQ1PA1x/GmmH9dWdUIjIAi10ud+T7L0g09uQe836MDhXexjU4dRx2/oXHfMC5RYLi+ebGUPlWmEreXIN0t2YxGKjykjPQf+l6TDG6ICeFBjMA/1xxToQbtKGBXIUghDYr9HDmpTiso05ML9/S3weo7+YVoqruUb57Jl11v7Mokejt4eqtLYKM9kiQsEL9QyYQj1lf1QEI3Y5/CkAPzq5Z52cQ1s84AVtUR8b8IOPhuhhqRRbvltTapHYarN1fgVNApFTsn+5uFedMv0lzKRQHEfZlEBuwkg=
  bucket: dh4
  skip_cleanup: true
  local_dir: build
  upload-dir: mupen64plus-qt
  on:
    all_branches: true
    condition: $TRAVIS_PULL_REQUEST = false
- provider: releases
  api_key:
    secure: BxDOO5XecOYTtpivcT/9aIW+oxOLO0U4J96Tc1QTpQOu50qlnXUanPsXvF3tSOari9tFvpxDgRt+OJeYCwL6fw/oG2n8TlGjt7XSEZ6bKZ1n3TW/lESUpE2c9gKFHCvBbepW1addkyBW+T6FmXz2rwDzy/fKSShgeT8NfZaczsPMQe1TWS6alRNtHbMtwNT1gqoH1JdgXFo2zvcZFSVVpILnOtIJ8iPuyjGNgtLd5Tx/6gjtI5MPXM9PsmIjealyYUQ8arnw2jiHx3sRtP03AAZdAhwM3AaWXkjGLGFA2kj/Lxf2Ly+EMbPwLY3Q0lMEZxVU5SdQzs2c/YmbN3DNTIkaOgnJc3Pj/hZB7I+kJuZA2OchmsvIrRoldMNX6sIoABjLiVeTEvDQoFV+F4Ynyg2FEk0R8spb2S6qr3lr7QIH4Y83oeVOzb09SvcFT0ub/Q7OqwGwLOg5+jA3bBTbWLCpDW1eo7SlemSKN4RG8uj91aHDh1eUW8IPd7yg+EhNJnKU4+6vfyaEM39BfME/q2Y7kcw/DCmOoqn6nvifIjxdM3YGJS3vybtQf5+chrpn50Rdo805uddlTjk7Zi8xsBSpUcQOeCywDo19kjeC6WngDRbUFOSvVmhw7elKvU9ghNccdiX3qm+0ylfI7rRjFvSBaQxEf1QtWtzZFcjZkdM=
  skip_cleanup: true
  file_glob: true
  file: build/*/mupen64plus-qt_*
  on:
    tags: true
